name: lab-ci
on:
  push: { branches: ["**"] }
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential checksec
      - name: Build lab bins
        run: make -C lab
      - name: Static checks (sin evidencias)
        run: |
          file lab/bins/* || true
          checksec --file=lab/bins/bof || true
